services:
  web:
    image: yemlo2112/proyecto-final-devops:latest
    ports:
      - "80:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: proyecto_devops
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app_network

configs:
  prometheus_config:
    file: ./prometheus.yml

networks:
  app_network:
    driver: overlay

volumes:
  db_data: