services:
  web:
    image: yemlo2112/proyecto-final-devops:latest
    ports:
      - "80:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: proyecto_devops
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: overlay

volumes:
  db_data: